### ISSUE TITLE
希望得到授权

### ISSUE THREAD

**Issue by greenhat616** [vankai/hitokoto-pwa#2]
您好， 我是来自一言网(hitokoto.cn)的开发者兼运维。
v2 一直苦于没有良好的首页交互， 我们发现您的设计十分符合我们对于未来排版以及交互的定位。 所以希望您能够授权我们使用您的开源代码进行修改， 并闭源运营。 十分感谢！

**Comment by eynol** [comment]
可以的，一开始这个就是想拿给酷儿用的，不过那个时候他没有时间支持这件事（API接口之类的，所以自己又做了个hitokoto-pwa-backend的后台）。有什么不明白的可以提issue。

**Comment by greenhat616** [comment]
好的， 十分感谢
